#pragma checksum "..\..\Menu2.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "73BD9B51860D23560AF2E14618CE6BEED0CA1CF3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SourceChord.FluentWPF;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using _1001_Docus__Desktop;


namespace _1001_Docus__Desktop {
    
    
    /// <summary>
    /// Menu2
    /// </summary>
    public partial class Menu2 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\Menu2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button hdd;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\Menu2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button sdd;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\Menu2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button mdd;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\Menu2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ld2;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/1001 Docus -Desktop;component/menu2.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Menu2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.hdd = ((System.Windows.Controls.Button)(target));
            
            #line 12 "..\..\Menu2.xaml"
            this.hdd.Click += new System.Windows.RoutedEventHandler(this.hdd_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.sdd = ((System.Windows.Controls.Button)(target));
            
            #line 13 "..\..\Menu2.xaml"
            this.sdd.Click += new System.Windows.RoutedEventHandler(this.sdd_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.mdd = ((System.Windows.Controls.Button)(target));
            
            #line 14 "..\..\Menu2.xaml"
            this.mdd.Click += new System.Windows.RoutedEventHandler(this.mdd_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ld2 = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\Menu2.xaml"
            this.ld2.Click += new System.Windows.RoutedEventHandler(this.ld2_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

